apiVersion: apps/v1
kind: Deployment
metadata:
  name: miportfolio
  namespace: miportfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miportfolio
  template:
    metadata:
      labels:
        app: miportfolio
    spec:
      # AQUÍ ESTÁ LA MAGIA: Le decimos que use tu secreto de Docker Hub
      imagePullSecrets:
        - name: regcred
      containers:
        - name: miportfolio
          image: franparradaw/ptaller-webserver:latest
          imagePullPolicy: Always # Obliga a descargar siempre la última versión de Jenkins
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"