pipeline {
    agent any

    stages {
        stage('Clonar repo ok'){
            steps{
                // Agrega el parámetro credentialsId
                git branch: 'main', 
                    credentialsId: 'fran', 
                    url: 'https://github.com/MAX-Franek/Despliege.git'
            }
        }
        // stage('Checkout'){
        //     steps {
        //         echo "Repo clonado los caracole"
        //         sh 'ls -la'
        //     }
        // }
        stage('Info'){
            steps {
                sh 'git rev-parse --short HEAD'
                sh 'sleep 300'
            }
        }
    }
}